### PR TITLE
Ensure empty expression tokens ranges are correct

### LINKED ISSUE #28: Possible token error
When parsing this code:

```
<a>{/* this is a comment */}</a>;
```

The token for `}` appears to have an incorrect range:

```js
  { type:
     { label: '}',
       keyword: undefined,
       beforeExpr: false,
       startsExpr: false,
       isLoop: false,
       isAssign: false,
       prefix: false,
       postfix: false,
       binop: null,
       updateContext: [Function] },
    value: undefined,
    start: 4,
    end: 28 }
```

With a range of `[4, 28]`, calling `code.slice(token.start, token.end)` includes the comment before the `}`. Is this intentional?

### PR DESCRIPTION
**Pull request by nzakas**
Turned out a little bit of trickery in parsing empty expressions was the cause. Still trying to learn how location is calculated, so let me know if this change makes sense.

Fixes #28

### CODE REVIEW

File: inject.js [hunk 1]
```diff
@@ -244,15 +244,17 @@ module.exports = function(acorn) {
...
   pp.jsx_parseEmptyExpression = function() {
-    var tmp = this.start;
+    var tmp = this.start, originalStart = this.start, node;
     this.start = this.lastTokEnd;
     this.lastTokEnd = tmp;
 
     tmp = this.startLoc;
     this.startLoc = this.lastTokEndLoc;
     this.lastTokEndLoc = tmp;
+    node = this.startNode();
```
Comment (RReverser) [inline inject.js]: With current Acorn API I think we can just use `startNodeAt` for this.

File: test/tests-jsx.js [hunk 2]
```diff
@@ -3634,10 +3634,78 @@ var fbTestFixture = {
 if (typeof exports !== "undefined") {
   var test = require("./driver.js").test;
   var testFail = require("./driver.js").testFail;
+  var tokTypes = require("../").tokTypes;
 }
 
 testFail("var x = <div>one</div><div>two</div>;", "Adjacent JSX elements must be wrapped in an enclosing tag (1:22)");
 
+test('<a>{/* foo */}</a>', {}, {
+  ranges: true,
```
Comment (RReverser) [inline test/tests-jsx.js]: `ranges` and `loose` are not needed in this case - first one checks `range` props and second marks test as such that shouldn't be checked against loose parser - which JSX doesn't have anyway.

**Comment by nzakas** [comment]
Updated to use `startNodeAt()` and `finishNodeAt()`.

**Comment by RReverser** [comment]
Thanks! Finally this awful hack I had to use back when writing this is gone. :fireworks:
